"""init schema

Revision ID: bc629694ac00
Revises: 
Create Date: 2025-09-29 17:17:23.312003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc629694ac00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('studio_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_id'), 'studios', ['id'], unique=False)
    op.create_index(op.f('ix_studios_name'), 'studios', ['name'], unique=True)
    op.create_index(op.f('ix_studios_studio_email'), 'studios', ['studio_email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'trainer', 'trainee', name='role_enum'), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_studio_id'), 'users', ['studio_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trainee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=15), nullable=True),
    sa.Column('number_of_week_training', sa.Integer(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('ai_status', sa.String(length=16), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_json', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_trainee_profiles_user_id')
    )
    op.create_index(op.f('ix_trainee_profiles_id'), 'trainee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_trainee_profiles_user_id'), 'trainee_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainee_profiles_user_id'), table_name='trainee_profiles')
    op.drop_index(op.f('ix_trainee_profiles_id'), table_name='trainee_profiles')
    op.drop_table('trainee_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_studio_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_studios_studio_email'), table_name='studios')
    op.drop_index(op.f('ix_studios_name'), table_name='studios')
    op.drop_index(op.f('ix_studios_id'), table_name='studios')
    op.drop_table('studios')
    # ### end Alembic commands ###
